// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v3.20.3
// source: protos/reverse.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReverseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Original      string                 `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"` // The original string to reverse
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReverseRequest) Reset() {
	*x = GetReverseRequest{}
	mi := &file_protos_reverse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReverseRequest) ProtoMessage() {}

func (x *GetReverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reverse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReverseRequest.ProtoReflect.Descriptor instead.
func (*GetReverseRequest) Descriptor() ([]byte, []int) {
	return file_protos_reverse_proto_rawDescGZIP(), []int{0}
}

func (x *GetReverseRequest) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

type GetReverseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // The reversed string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReverseResponse) Reset() {
	*x = GetReverseResponse{}
	mi := &file_protos_reverse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReverseResponse) ProtoMessage() {}

func (x *GetReverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reverse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReverseResponse.ProtoReflect.Descriptor instead.
func (*GetReverseResponse) Descriptor() ([]byte, []int) {
	return file_protos_reverse_proto_rawDescGZIP(), []int{1}
}

func (x *GetReverseResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_protos_reverse_proto protoreflect.FileDescriptor

var file_protos_reverse_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x22,
	0x2f, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c,
	0x22, 0x2c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x57,
	0x0a, 0x0e, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x45, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x1a,
	0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x76, 0x65,
	0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x65, 0x76,
	0x65, 0x72, 0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_reverse_proto_rawDescOnce sync.Once
	file_protos_reverse_proto_rawDescData = file_protos_reverse_proto_rawDesc
)

func file_protos_reverse_proto_rawDescGZIP() []byte {
	file_protos_reverse_proto_rawDescOnce.Do(func() {
		file_protos_reverse_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_reverse_proto_rawDescData)
	})
	return file_protos_reverse_proto_rawDescData
}

var file_protos_reverse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_reverse_proto_goTypes = []any{
	(*GetReverseRequest)(nil),  // 0: reverse.GetReverseRequest
	(*GetReverseResponse)(nil), // 1: reverse.GetReverseResponse
}
var file_protos_reverse_proto_depIdxs = []int32{
	0, // 0: reverse.ReverseService.GetReverse:input_type -> reverse.GetReverseRequest
	1, // 1: reverse.ReverseService.GetReverse:output_type -> reverse.GetReverseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_reverse_proto_init() }
func file_protos_reverse_proto_init() {
	if File_protos_reverse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_reverse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_reverse_proto_goTypes,
		DependencyIndexes: file_protos_reverse_proto_depIdxs,
		MessageInfos:      file_protos_reverse_proto_msgTypes,
	}.Build()
	File_protos_reverse_proto = out.File
	file_protos_reverse_proto_rawDesc = nil
	file_protos_reverse_proto_goTypes = nil
	file_protos_reverse_proto_depIdxs = nil
}
